CREATE TABLE CONTATO (
	CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(60) NOT NULL,
	ENDERECO VARCHAR(150) NOT NULL,
	TELEFONE VARCHAR(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;